eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 10001
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jguo
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      time-to-live: 120000

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  file:
    path: D:\elk

#Prometheus springboot监控配置
management:
  tracing:
    sampling:
      probability: 1