spring:
  application:
    name: service-reg-center

server:
  port: 10000

logging:
  level:
    org:
      springframework:
        web: INFO

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

#Prometheus springboot监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name} # 暴露的数据中添加application label
  prometheus:
    metrics:
      export:
        enabled: true