eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 10002
spring:
  application:
    name: ui-service
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      time-to-live: 120000

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  file:
    path: D:\elk

#Prometheus springboot监控配置
management:
  tracing:
    sampling:
      probability: 1
